### PR TITLE
DB2 analytics service in bluemix is now called dashDB

### PR DESCRIPTION
**Pull request by mariobriggs**
Also Dmitry, how can we have you work off the location where you will get the latest DB2 ODBC/CLI bundle? There have been many simplifications around SSL in the DB2 ODBC/CLI which users will want ?

### CODE REVIEW

**Comment by dintel** [comment]
Can you provide new location where DB2 CLI can be downloaded or do you want us to store DB2 CLI and send us updated CLI?

**Comment by dintel** [comment]
Can you also please merge your 3 commits into single one? 3 commits for a single changed line is overkill.

**Comment by mariobriggs** [comment]
Here is the location which will always be most current version - https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz

As for the 3 commits, what i tried was to update the buildpack to pull from above location. However the untar was not working (not sure if the entire path is required in the untar). so the additional 2 commits were roll back of that

**Comment by dintel** [comment]
Is dashDB a replacement for BLUAcceleration?
How can I test dashDB? I see that dashDB does not have free plan.

**Comment by mariobriggs** [comment]
replacement - Yes (it was a name change). The entry plan has a free tier i.e. as long as you store less than 1 GB data, it is free. (I dont think you need more than 1 GB storage for your test :-) )

**Comment by mariobriggs** [comment]
@dintel can chip in on this one - https://developer.ibm.com/answers/questions/175422/zend-db2.html

**Pull request merged**
